

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class JanelaBaixo extends javax.swing.JFrame {

    public Baixo b1;
    private static GerBaixo gerBaixo = new GerBaixo();
    
    private static JanelaBaixo janelaBaixo1;
    
    /**
     * Creates new form JanelaBat
     */
    public JanelaBaixo() {
        initComponents();
    }
    
    public static JanelaBaixo getJanelaBaixo(){
        if(janelaBaixo1 == null){
            janelaBaixo1 = new JanelaBaixo();
        }
        return janelaBaixo1;
    }
    
    public static GerBaixo getGerBaixo(){
        return gerBaixo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarca = new javax.swing.JLabel();
        btCad = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        lblBaixo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        lblCaptador = new javax.swing.JLabel();
        lblQtdCordas = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtCaptador = new javax.swing.JTextField();
        txtQtdCordas = new javax.swing.JTextField();
        TabBaixo1 = new javax.swing.JScrollPane();
        tabBaixo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Janela Bateria");
        setResizable(false);

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMarca.setText("Marca:");

        btCad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCad.setText("Cadastrar");
        btCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadActionPerformed(evt);
            }
        });

        btAlterar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btConsultar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        txtTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblBaixo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBaixo.setText("Baixo");

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCodigo.setText("Codigo:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipo.setText("Tipo: ");

        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblModelo.setText("Modelo:");

        lblCaptador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCaptador.setText("Captador:");

        lblQtdCordas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQtdCordas.setText("Quantidade de Cordas:");

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPreco.setText("Preço:");

        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtCaptador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtQtdCordas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tabBaixo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Tipo", "Marca", "Modelo", "Captador", "QtdCordas", "Preço"
            }
        ));
        TabBaixo1.setViewportView(tabBaixo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btConsultar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCad)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btAlterar)))
                        .addGap(103, 103, 103)
                        .addComponent(btExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addGap(74, 74, 74)
                .addComponent(btSair)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCodigo)
                            .addGap(18, 18, 18)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTipo)
                                .addComponent(lblMarca)
                                .addComponent(lblModelo)
                                .addComponent(lblCaptador)
                                .addComponent(lblPreco)
                                .addComponent(lblQtdCordas))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCaptador, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtQtdCordas, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblBaixo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabBaixo1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBaixo)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModelo))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCaptador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCaptador))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdCordas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdCordas))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreco)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(TabBaixo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btLimpar)
                            .addComponent(btSair))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCad)
                            .addComponent(btConsultar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btExcluir)
                            .addComponent(btAlterar))
                        .addGap(32, 32, 32))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadActionPerformed
        cadastrar();
        listarTab();
    }//GEN-LAST:event_btCadActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterar();
        listarTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
        listarTab();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    public void excluir(){
        b1 = new Baixo();
        
        b1.setCodigo(txtCodigo.getText());
        
        b1 = gerBaixo.consultaCodigo(b1);
        
        if(b1 != null){
            
            txtCodigo.setText(b1.getCodigo());
            txtTipo.setText(b1.getTipo());
            txtMarca.setText(b1.getMarca());
            txtModelo.setText(b1.getModelo());
            txtCaptador.setText(b1.getCaptador());
            txtQtdCordas.setText(Integer.toString(b1.getQtdCordas()));
            txtPreco.setText(Integer.toString(b1.getVenda1().getPreco()));
            

            int perg = JOptionPane.showConfirmDialog(null, "Deseja excluir?", 
                                   "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);
            if(perg == 0){
                gerBaixo.excluirBaixo(b1);
                JOptionPane.showMessageDialog(null, "Sucesso na exclusão", "Exclusão", 1);
                
            }
            
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Baixo não cadastrado", "Erro na Consulta", 0);
            limpar();
        }
    }
    
    public void alterar(){
        b1 = new Baixo();
        
        b1.setCodigo(txtCodigo.getText());
        
        b1 = gerBaixo.alteraBaixo(b1);
        
        if(b1 != null){
            txtCodigo.setText(b1.getCodigo());
            txtTipo.setText(b1.getTipo());
            txtMarca.setText(b1.getMarca());
            txtModelo.setText(b1.getModelo());
            txtCaptador.setText(b1.getCaptador());
            txtQtdCordas.setText(Integer.toString(b1.getQtdCordas()));
            txtPreco.setText(Integer.toString(b1.getVenda1().getPreco()));
            JOptionPane.showMessageDialog(null, "Sucesso na alteração de dados", "Alteração", 1);
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Bateria não cadastrada", "Erro na Consulta", 0);
            limpar();
        }
    }
    
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabBaixo.getModel();
        int i = 0;
        
        modelo.setRowCount(i);
        
        for(Baixo b1 : gerBaixo.getBdBaixo()){
            modelo.insertRow(i, new Object[]{b1.getCodigo(), b1.getTipo(), b1.getMarca(), 
                    b1.getModelo(), b1.getCaptador(), b1.getQtdCordas(), b1.getVenda1().getPreco()});
            i++;
        }
    }
    
    public void consultar(){
        b1 = new Baixo();
        
        b1.setCodigo(txtCodigo.getText());
        
        b1 = gerBaixo.consultaCodigo(b1);
        
        if(b1 != null){
            txtCodigo.setText(b1.getCodigo());
            txtTipo.setText(b1.getTipo());
            txtMarca.setText(b1.getMarca());
            txtModelo.setText(b1.getModelo());
            txtCaptador.setText(b1.getCaptador());
            txtQtdCordas.setText(Integer.toString(b1.getQtdCordas()));
            txtPreco.setText(Integer.toString(b1.getVenda1().getPreco()));
            JOptionPane.showMessageDialog(null, "Sucesso na consulta", "Consulta", 1);
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Bateria não cadastrada", "Erro na Consulta", 0);
            limpar();
        }
    }
    
    public void cadastrar(){
        b1 = new Baixo();
        
        
        b1.setCodigo(txtCodigo.getText());
        b1.setTipo(txtTipo.getText());
        b1.setMarca(txtMarca.getText());
        b1.setModelo(txtModelo.getText());
        b1.setCaptador(txtCaptador.getText());
        b1.setQtdCordas(Integer.parseInt(txtQtdCordas.getText()));
        b1.getVenda1().setPreco(Integer.parseInt(txtPreco.getText()));
        
                
        b1 = gerBaixo.cadBaixo(b1);
        
        if(b1 != null){
            JOptionPane.showMessageDialog(null, "Baixo cadastrado com sucesso", 
                        "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            limpar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Baixo já possui cadastro", 
                        "Erro no cadastro", JOptionPane.ERROR_MESSAGE);
            limpar();
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, 
                "Deseja Sair?", 
                "Sair", 
                JOptionPane.YES_NO_OPTION);
        if(resp == 0){
            this.dispose();
        }
    }
    
    public void limpar(){
        txtCodigo.setText("");
        txtTipo.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtCaptador.setText("");
        txtQtdCordas.setText("");
        txtPreco.setText("");
        txtCodigo.requestFocus();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaBaixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaBaixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaBaixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaBaixo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaBaixo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabBaixo1;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCad;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel lblBaixo;
    private javax.swing.JLabel lblCaptador;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQtdCordas;
    private javax.swing.JLabel lblTipo;
    private static javax.swing.JTable tabBaixo;
    private javax.swing.JTextField txtCaptador;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtdCordas;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
